vite, vitest and supertest added. Problem with import app.
IT-Academy-BCN/ita-directory pull request #536
Opened 2022-04-08 06:17 UTC by Cabirol

Te hago un pull request aún siendo consciente de que el issue está incompleto, ya que estoy encallado. He instalado supertest y vitest (además de vite, que es necesario para vitest). He añadido el script "test": "vitest". Pero los test que involucran el elemento app (es decir, para testear los endpoints, todos) no funcionan. La línea que da problemas es la 16 de de app.test.js, que es la que importa app de app.js. El error parece estar relacionado con el archivo initRedis.js. No he podido averiguar de qué se trata. A continuación el mensaje de error:

 FAIL  app/_tests_/app.test.js [ app/_tests_/app.test.js ]
TypeError: Invalid URL
 ❯ Function.parseURL node_modules/@node-redis/client/dist/lib/client/index.js:113:76
 ❯ Commander._RedisClient_initiateOptions node_modules/@node-redis/client/dist/lib/client/index.js:294:36
 ❯ new RedisClient node_modules/@node-redis/client/dist/lib/client/index.js:77:148
 ❯ new Commander node_modules/@node-redis/client/dist/lib/commander.js:18:17
 ❯ create node_modules/@node-redis/client/dist/lib/client/index.js:109:16
 ❯ Object.createClient node_modules/redis/dist/index.js:25:38
 ❯ Object.<anonymous> app/utils/initRedis.js:3:22

2022-05-17 20:02 UTC, tonikny commented
Ya funcionan los tests y de paso he corregido algún bug ;)

2022-05-23 07:08 UTC, kevinmamaqi requested changes

2022-05-23 07:08 UTC, kevinmamaqi commented on backend/app/routes/users.routes.js
> +// router.get('/', authenticateToken, UsersController.getAllUsers)
Volver a habilitar.

2022-05-23 07:08 UTC, kevinmamaqi commented on backend/app/_tests_/app.test.js
> +describe('test control, eliminar luego', () => {
Eliminar

2022-05-24 06:01 UTC, kevinmamaqi approved these changes

2022-05-24 06:01 UTC, merged