511 add change password page
IT-Academy-BCN/ita-directory pull request #720
Opened 2022-09-20 09:07 UTC by adaldin

Displaying change password page.  
Missing from backend:
-On requesting  'recover-password', a 'status 500 error' appears on console:
POST http://localhost:10910/api/v1/recover-password 500 (Internal Server Error)
-On the fetch/XHR 'recover-password': 
 message : "\nInvalid `prisma.user.findUnique()` 

linked to issue # 721 Fix recover password request on ITA-API

2022-09-20 09:09 UTC, kevinmamaqi commented
@adaldin explain what is missing from the backend and/or link the other issue.

2022-09-20 09:10 UTC, kevinmamaqi requested changes

2022-09-20 09:10 UTC, kevinmamaqi commented on frontend/src/pages/UserFlow/RecoverPassword/RecoverPassword.jsx
> +      await axios.post(`${import.meta.env.VITE_API_URL}/recover-password`, data)
Aquí debería de ser un objeto, al cambiar email por data, continuas enviando un string (creo), y deberías enviar un objeto { email: valorEmail }. Si usas solo { email } ya coge email como propiedad y el valor se le asigna automáticamente.

2022-09-20 10:30 UTC, adaldin commented on frontend/src/pages/UserFlow/RecoverPassword/RecoverPassword.jsx
> +      await axios.post(`${import.meta.env.VITE_API_URL}/recover-password`, data)
Había hecho el console de data y lo imprime como objeto, por eso lo he puesto así. Aquí una captura del console:
![Captura de Pantalla 2022-09-20 a la(s) 12 28 37](https://user-images.githubusercontent.com/18453013/191235270-c854d626-9b34-44c9-975a-f48ad535c590.png)

2022-09-21 09:33 UTC, kevinmamaqi approved these changes

2022-09-21 09:33 UTC, merged