719 readme local setup
IT-Academy-BCN/ita-directory pull request #722
Opened 2022-09-20 11:21 UTC by lauracapella

En el readme he actualizado los pasos del setup para el proyecto en local

2022-09-20 11:27 UTC, kevinmamaqi requested changes

2022-09-20 11:27 UTC, kevinmamaqi commented on README.md
> +5. Once all of it is up and running launch the backend, to enable the API and the frontend (if necessary) in 2 different terminals.
Aquí añadiria una imagen de VSCode y explicaria un poco más a que te refieres @lauracapella

2022-09-21 10:09 UTC, lauracapella commented on README.md
> +5. Once all of it is up and running launch the backend, to enable the API and the frontend (if necessary) in 2 different terminals.
He subido los cambios con una explicación más detallada y añadiendo un screenshot

2022-09-21 10:14 UTC, lauracapella commented on README.md
> +5. Once all of it is up and running launch the backend, to enable the API and the frontend (if necessary) in 2 different terminals.
Tengo una duda, he añadido la imagen screenshot en la raiz, misma ruta donde está ubicado el logo. No se si es mejor cambiar estas imágenes de directorio.

2022-09-21 10:28 UTC, kevinmamaqi-90poe approved these changes

2022-09-21 10:29 UTC, kevinmamaqi approved these changes

2022-09-21 10:29 UTC, merged