001 horizontal scroll
IT-Academy-BCN/ita-directory pull request #725
Opened 2022-09-27 11:23 UTC by JordiNodeJS

I've fixed it on GlobalStyle component

2022-09-28 09:36 UTC, kevinmamaqi requested changes

2022-09-28 09:36 UTC, kevinmamaqi commented on frontend/src/theme/globalStyles.js
> +    font-family: ${font.fontFamily};
No debería de estar en el global styles. La causa debe ser otra.

2022-09-29 11:10 UTC, JordiNodeJS commented on frontend/src/index.jsx
> +import 'normalize.css'
Añado el normalize pero no veo que afecte a los elementos que me dan problemas

2022-09-29 11:15 UTC, JordiNodeJS commented on frontend/src/components/layout/Header/Header.jsx
> +  padding: 10px 0;
He probado esta solución(_padding_) y añadiendo  _box-sizing: border-box_  y arreglan el problema. Aunque el box-sizing se viene aplicando desde el body, por lo que he pensado que la mejor solucción o el problema viene del padding, que aunque se aplique desde el border hacia adentro acaba por hacer la caja **más grande** y empuja a que el div desborde por los bordes izquierdo y derecho.

2022-09-29 11:19 UTC, JordiNodeJS commented on frontend/src/theme/globalStyles.js
> -
si añado: 
`
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
`
1ª Solucciona el problema del horizontal scroll en el login y register, pero descoloca el formulario.
2ª Estas reglas deberían aplicarse ya desde normalize.css y no reescribirlas de nuevo en el globalStyles

2022-10-01 14:23 UTC, JordiNodeJS commented on frontend/src/theme/globalStyles.js
> +  div {
He optado por aplicar el box-sizing sólo a los divs, de lo contrario descuadra  muchos otros elementos de la web.

2022-10-01 14:25 UTC, JordiNodeJS commented on frontend/src/index.jsx
> +import 'normalize.css'
Añado el reseteo de los estilos básicos con normalize, pero veo que sólo aplica box-sizing a determinados elementos que dan problemas en determinados browsers,  por  lo que en aplico el box-sizing en el globalStyles.

2022-10-04 17:44 UTC, JordiNodeJS commented on frontend/src/index.jsx
> +import './modern-normalize.css'
El test mira si existe esta línea de código en el archivo. Si exite da positivo, si no negativo, si está comentada también negativo.

2022-10-05 07:06 UTC, kevinmamaqi commented on frontend/src/index.jsx
> +import './modern-normalize.css'
No dejes comentarios, el código ha de explicarse por si mismo.

2022-10-05 09:46 UTC, kevinmamaqi requested changes

2022-10-06 09:17 UTC, kevinmamaqi requested changes

2022-10-06 09:17 UTC, kevinmamaqi commented on frontend/package.json
> +    "modern-normalize": "^1.1.0",
Las dependencias han de estar congeladas. Sin el `^`

2022-10-06 09:17 UTC, kevinmamaqi commented on frontend/src/App.jsx
> +
Quitar el hueco en blanco.

2022-10-06 09:17 UTC, kevinmamaqi commented on frontend/src/__test__/index.test.jsx
> +/* eslint-disable jest/valid-expect-in-promise */
Quitar este comentario y refactorizar el código.

2022-10-06 09:17 UTC, kevinmamaqi commented on frontend/src/pages/Home/Home.jsx
> +const HomeContainer = styled(Container).attrs({ role: 'container', title: 'Home' })`
¿Por qué se le añade la propiedad title?

2022-10-06 11:06 UTC, JordiNodeJS commented on frontend/src/__test__/index.test.jsx
> +/* eslint-disable jest/valid-expect-in-promise */
He intentado refactorizarlo con asinc away y el test peta, dándome un error de tiempo. Por eso utilizo promesas al estilo clásico con .then y al utilizarlo me salta una alarma de linter, que así no quiere que lo escriba y por eso desactivo esa regla. No se me ocurre otra manera de hacerlo.

2022-10-10 10:26 UTC, kevinmamaqi-90poe requested changes

2022-10-10 10:26 UTC, kevinmamaqi-90poe commented on frontend/src/pages/Home/Home.jsx
> +const HomeContainer = styled(Container).attrs({ role: 'container', title: 'Home' })`
Añade data-testid en `<HomeContainer data-testid="homeContainerTest"></...>`

2022-10-10 10:26 UTC, kevinmamaqi-90poe commented on frontend/src/__test__/index.test.jsx
> +  })
`}, 15_000)`

2022-10-10 16:53 UTC, kevinmamaqi approved these changes

2022-10-10 20:56 UTC, kevinmamaqi approved these changes

2022-10-10 20:56 UTC, merged