733 add custom render provider for testing
IT-Academy-BCN/ita-directory pull request #734
Opened 2022-10-06 10:02 UTC by adaldin

2022-10-06 10:12 UTC, kevinmamaqi requested changes

2022-10-06 10:12 UTC, kevinmamaqi commented on frontend/src/components/layout/Header/UserAccess.jsx
> +
La línea vacia porque si chirria.

2022-10-06 10:12 UTC, kevinmamaqi commented on package.json
> +    "@testing-library/user-event": "^14.4.3",
evitar el `^` siempre que se pueda para tener las mismas versiones y evitar indicar que soporta actualizaciones.

2022-10-06 21:27 UTC, kevinmamaqi commented on frontend/src/__test__/test-utils.jsx
> +// eslint-disable-next-line react/prop-types
Esta linea entiendo se puede quitar como vimos por la mañana.

2022-10-07 06:47 UTC, kevinmamaqi-90poe approved these changes

2022-10-07 06:47 UTC, adaldin reviewed
🤦🏽‍♀️ Ahora sí!

2022-10-07 06:47 UTC, adaldin commented on frontend/src/__test__/test-utils.jsx
> +// eslint-disable-next-line react/prop-types
🤦🏽‍♀️ Ahora sí!

2022-10-07 06:50 UTC, kevinmamaqi approved these changes

2022-10-07 06:50 UTC, merged