693 fix control modals from user admins page
IT-Academy-BCN/ita-directory pull request #763
Opened 2022-10-25 08:49 UTC by adaldin

He vuelto a una versión antigua de lo que tengo porque no me permite hacer el push por los files de backend. Pero aquí me vuelve a dar conflicto con los archivos que no aparecen.  El problema estaba en el modal y que no tenía un alto definido pero sí el overflow-y. Se ha fijado el height y permite el scroll.

2022-10-25 09:36 UTC, kevinmamaqi requested changes

2022-10-25 09:36 UTC, kevinmamaqi commented on frontend/src/components/organisms/Modal/Modal.styles.js
> +      height: 10rem;
El alto fijo por defecto me parece que no debería de ser necesario. Quizas un min-height si lo que quieres es que no tenga menos de X.

2022-10-25 09:36 UTC, kevinmamaqi commented on frontend/src/modern-normalize.css
> +@import 'modern-normalize';
Creo que este archivo se eliminaba. ¿Has vuelto a descargar main y hacer un rebase?

2022-10-26 09:07 UTC, adaldin commented
Vale, creo que ahora sí. Cada vez que hago un pull a la rama donde trabajo, me borra los archivos de back. Creo que ahora están  todos ya, está borrado el modern-normalize, y he actualizado el modalBody de height a max-height, ya que como el formulario tiene una altura muy grande, pero los modales de cambiar estado, y borrar no, me parecía que mejor limitarlo a un máximo de altura y que haga scroll y no setear una altura fija que modificara los otros modales.

2022-10-26 09:14 UTC, adaldin commented on backend/package.json
> +    "@prisma/client": "^4.4.0",
He hecho el pull desde main  y he resuelto el conflicto dejándolo en la versión anterior que es la que estaba (no se porqué me ha actualizado esto y borrado los files)

2022-10-26 09:15 UTC, adaldin commented on frontend/src/components/organisms/Modal/Modal.styles.js
> +      height: 10rem;
He actualizado el modalBody de height a max-height, ya que como el formulario tiene una altura muy grande, pero los modales de cambiar estado y borrar user no, me parecía que era mejor limitarlo a un máximo de altura y que haga scroll y no setear una altura fija que modificara los otros modales.

2022-10-26 09:23 UTC, kevinmamaqi approved these changes

2022-10-26 09:23 UTC, merged