631 add react helmet async
IT-Academy-BCN/ita-directory pull request #767
Opened 2022-10-26 07:43 UTC by BoccoSantiago

2022-10-26 08:21 UTC, kevinmamaqi commented
@BoccoSantiago asignate el PR a ti y a mi ponme como reviewer.

2022-10-26 08:24 UTC, kevinmamaqi requested changes

2022-10-26 08:24 UTC, kevinmamaqi commented on frontend/.eslintrc
> +    "react/prop-types":["off"],
Esto tiene que estar como ERROR

2022-10-26 08:24 UTC, kevinmamaqi commented on frontend/package.json
> +    "react-helmet-async": "^1.3.0",
Instala la última version especifica. Es decir `npm install packageName@1.3.0`

2022-10-26 08:24 UTC, kevinmamaqi commented on frontend/src/pages/AdList/AdList.jsx
> +import HelmetComponent from '../../components/organisms/HelmetComponent'
exporta desde el archivo index.js de organisms

2022-10-26 08:24 UTC, kevinmamaqi commented on frontend/src/pages/AdList/AdList.jsx
> +      <HelmetComponent text="Mis anuncios" />
Incluye el texto como una propiedad title de Body, y renderiza HelmetComponent solo dentro de Body.

2022-10-26 08:24 UTC, kevinmamaqi commented on package.json
> +    "react-helmet-async": "^1.3.0"
Esto no tiene sentido en el directorio principal. El react-helmet-async... Debería de estar solo en frontend.

2022-10-26 11:34 UTC, kevinmamaqi commented
@BoccoSantiago Hay errores en el lint

2022-10-27 09:34 UTC, kevinmamaqi commented
Creo que SonarCloud esta fallando y que la manera es añadirlo en el Render.  @adaldin ¿Puedes echarle una mano?

2022-10-31 07:49 UTC, kevinmamaqi reviewed
Buen trabajo. Por favor añade un test para comprobar que el título se actualiza.

2022-11-02 13:20 UTC, kevinmamaqi commented
@BoccoSantiago aquí se estan cambiando todavía más archivos.

2022-11-02 13:49 UTC, BoccoSantiago commented
> @BoccoSantiago aquí se estan cambiando todavía más archivos.

al realizar el rebase me salieron muchisimos cambios, creo que voy a cerrar esta rama y crear un nueva.

2022-11-02 14:28 UTC, closed without merging