685 avoid regeneration of zod schemas
IT-Academy-BCN/ita-directory pull request #770
Opened 2022-10-26 10:05 UTC by fbages

Checks if zod schema already exists, if not zod schema is created

2022-10-26 13:27 UTC, kevinmamaqi commented
@fbages rellena la columna de la derecha por favor

2022-10-26 14:07 UTC, fbages commented on backend/prisma/itaGenerator.js
> +    console.log(outputDir)
Hecho

2022-10-26 14:29 UTC, fbages commented on backend/prisma/itaGenerator.js
> +        if (data.replace(/\s/g, '') != output.replace(/\s/g, '')) {
Porque si se reescribe de nuevo, cuando el fichero ya existe con el mismo texto, no se evita la regeneración.

2022-10-26 14:37 UTC, kevinmamaqi commented on backend/prisma/itaGenerator.js
> +        if (data.replace(/\s/g, '') != output.replace(/\s/g, '')) {
Antes que el check, intentaria averiguar el porque. Si es el mismo texto, porque git no lo reconoce @tonikny

2022-10-26 14:38 UTC, kevinmamaqi requested changes

2022-10-26 14:38 UTC, kevinmamaqi commented on backend/prisma/itaGenerator.js
> +              console.error(err)
Eliminar los console.log() y tirar un error throw new ....

2022-10-26 20:43 UTC, kevinmamaqi commented on backend/prisma/itaGenerator.js
> +        if (data.replace(/\s/g, '') != output.replace(/\s/g, '')) {
Creo que tiene que ver con itaGenerator.js > fs.writeFile, quizas fs.writeFileSync lo solucione.

2022-10-27 10:47 UTC, kevinmamaqi commented
Hay un conflicto @fbages

2022-10-28 07:03 UTC, kevinmamaqi approved these changes

2022-10-28 07:03 UTC, merged