774 simplify forms creating new inputnumbergroup
IT-Academy-BCN/ita-directory pull request #779
Opened 2022-10-27 10:14 UTC by JordiNodeJS

2022-10-27 10:40 UTC, kevinmamaqi requested changes

2022-10-27 10:40 UTC, kevinmamaqi commented on frontend/src/components/molecules/CreateNewAdInputGroup.jsx
> +import inputComponentData from '../atoms/Forms/inputComponetData'
Esto no tiene sentido en este PR

2022-10-27 10:40 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/inputComponetData.js
> +import InputNumber from './InputNumber'
Este cambio no tiene sentido en este PR

2022-10-27 10:40 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/InputNumber.jsx
>      <InputNumberStyled>
En este nivel solo debería de estar el input

2022-10-31 08:32 UTC, kevinmamaqi requested changes
Muchas cosas estan mal. La principal es que inputNumberGroup debería de estar en Molecules. Aquí se esta añadiendo un nuevo input llamado InputText, no tiene sentido.

2022-10-31 08:32 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/InputText.jsx
> +  textStyles: PropTypes.oneOfType([PropTypes.object, PropTypes.string]),
Esta prop no se usa, y debería ser solo object.

2022-10-31 08:32 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/InputText.jsx
> +  inputStyles: PropTypes.oneOfType([PropTypes.object, PropTypes.string]),
Esta prop no se usa, y debería ser solo object.

2022-10-31 08:32 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/InputText.jsx
> +  labelStyles: PropTypes.oneOfType([PropTypes.object, PropTypes.string]),
Esta prop no se usa, y debería ser solo object.

2022-10-31 08:32 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/InputText.jsx
> +  id: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
Debería ser solo string

2022-10-31 08:32 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/InputText.jsx
> +  name: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
Debería ser solo string

2022-10-31 08:32 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/InputText.jsx
> +  min: PropTypes.number,
No se usa

2022-10-31 08:32 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/InputText.jsx
> +  max: PropTypes.number,
No se usa

2022-11-08 08:28 UTC, kevinmamaqi commented on .vscode/settings.json
>    },
Eliminar settings.json de .vscode, ignorarlo.

2022-11-08 08:40 UTC, JordiNodeJS commented on frontend/src/components/atoms/Forms/InputNum.jsx
> +Input.propTypes = {
El InputNum.jsx fue eliminado, no sé como tienes acceso a ese archivo.

2022-11-14 08:50 UTC, closed without merging