692 fix ads page ads display 1
IT-Academy-BCN/ita-directory pull request #780
Opened 2022-10-27 17:19 UTC by RogerRochoRibas

will close #692

2022-10-28 06:52 UTC, kevinmamaqi-90poe commented
Mira la duplicación. Quizas puedas tener un afterEach => clear y beforeEach => set.

2022-10-28 06:56 UTC, kevinmamaqi commented
Mira la duplicación. Quizas puedas tener un afterEach => clear y beforeEach => set.

2022-10-28 07:00 UTC, kevinmamaqi commented
En general buen trabajo, funciona, pero ahora faltan los tests

2022-10-28 07:01 UTC, kevinmamaqi requested changes

2022-10-31 07:52 UTC, kevinmamaqi approved these changes

2022-10-31 07:53 UTC, merged