757 fixed profile picture
IT-Academy-BCN/ita-directory pull request #784
Opened 2022-11-02 10:47 UTC by BoccoSantiago

2022-11-07 06:26 UTC, kevinmamaqi requested changes

2022-11-07 06:26 UTC, kevinmamaqi commented on frontend/src/components/layout/Header/UserAccess.jsx
> +const ImgStyle = styled.div`
¿No podría ser styled.img directamente?

2022-11-07 06:26 UTC, kevinmamaqi commented on frontend/src/pages/UserFlow/Profile/Profile.styles.js
> +export const ProfileImageStyle = styled.div`
Creo que se puede sustituir por el `FlexBox` de `wrapper.js` en la carpeta `theme`.

2022-11-07 10:11 UTC, BoccoSantiago commented on frontend/src/components/layout/Header/UserAccess.jsx
> +const ImgStyle = styled.div`
Creo que no porque ese styled component esta envolviendo otro componente, no tiene "src" propia.

2022-11-07 10:25 UTC, BoccoSantiago commented on frontend/src/pages/UserFlow/Profile/Profile.styles.js
> +export const ProfileImageStyle = styled.div`
No queda exactamente igual, pero puede funcionar, lo modifico? con <FlexBox/> la imagen queda sin algunos estilos como el borde blanco y la sombra.

2022-11-07 10:37 UTC, kevinmamaqi commented on frontend/src/components/layout/Header/UserAccess.jsx
> +const ImgStyle = styled.div`
Básciamente aquí envuelves en un div la image. ¿No podría ser la imagen directamente? o styled(ProfileImage)?

2022-11-07 10:37 UTC, kevinmamaqi commented on frontend/src/pages/UserFlow/Profile/Profile.styles.js
> +export const ProfileImageStyle = styled.div`
Haz styled(FlexBox) para reutilizar parte del mismo si es necesario y luego añadele otros estilos.

2022-11-08 10:03 UTC, kevinmamaqi commented
@BoccoSantiago ¿puedes añadir un test?

2022-11-09 07:28 UTC, kevinmamaqi approved these changes

2022-11-09 07:28 UTC, merged