Typescript set up
IT-Academy-BCN/ita-directory pull request #802
Opened 2022-11-14 09:56 UTC by fbages

2022-11-14 11:07 UTC, kevinmamaqi requested changes
Haz una prueba y pasa un archivo de .js a .ts, para ver si compila bien.

2022-11-14 11:07 UTC, kevinmamaqi commented on backend/.eslintrc
>    "rules": {
Creo que faltaria un parser definido aquí

2022-11-14 11:07 UTC, kevinmamaqi commented on backend/package.json
>      "eslint-plugin-prettier": "4.0.0",
Este creo que sobra, por favor revisa la documentación de prettier con linters.

2022-11-14 12:00 UTC, fbages commented on backend/.eslintrc
> +    "airbnb/hooks",
Hecho

2022-11-14 12:02 UTC, fbages commented on backend/.eslintrc
>    "rules": {
Hecho

2022-11-18 09:56 UTC, fbages commented
> Haz una prueba y pasa un archivo de .js a .ts, para ver si compila bien.
He modificado el archivo constrants.controller, también he creado un script "build" en package.json para compilar automáticamente de typescript a javascript y copiar todos los ficheros necesarios para levantar el server.js en la carpeta "dist"

2022-11-21 10:27 UTC, kevinmamaqi approved these changes

2022-11-21 10:27 UTC, merged