775 create new map input
IT-Academy-BCN/ita-directory pull request #807
Opened 2022-11-15 08:47 UTC by BoccoSantiago

2022-11-15 09:45 UTC, kevinmamaqi requested changes

2022-11-15 09:45 UTC, kevinmamaqi commented on frontend/.eslintrc
> +    //"airbnb-typescript",
Esto tiene que dejarse.

2022-11-15 09:45 UTC, kevinmamaqi commented on frontend/.eslintrc
> +  //"parser": "@typescript-eslint/parser",
Esto tiene que dejarse.

2022-11-15 09:45 UTC, kevinmamaqi commented on frontend/src/components/atoms/InputMap.jsx
> +      <Input type="text" value={value} placeholder={placeholder} onChange={onChange} name={name} />
Si es un type text, reusa el existente, no tiene mucho sentido usar uno nuevo.

2022-11-15 09:45 UTC, kevinmamaqi commented on frontend/src/components/organisms/Map/CustomMap/CustomMap.jsx
> +/* var myIcon = L.icon({
Si el código comentado no se utiliza, eliminarlo.

2022-11-15 13:18 UTC, kevinmamaqi requested changes

2022-11-15 13:18 UTC, kevinmamaqi commented on frontend/src/components/atoms/InputMap.jsx
> +      <Input type="text" value={value} placeholder={placeholder} onChange={onChange} name={name} />
Esto sigue siendo un problema! Esta duplicando el código de InputText @BoccoSantiago

2022-11-15 13:18 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/InputText.jsx
> +  setLocation: PropTypes.func,
Esta parece una función solo para el mapa, no para el InputText @BoccoSantiago

2022-11-15 13:23 UTC, BoccoSantiago commented on frontend/src/components/atoms/Forms/InputText.jsx
> +  setLocation: PropTypes.func,
tienes razon, me confundí, ya lo corrijo

2022-11-16 11:01 UTC, BoccoSantiago commented
Pending for issue #808 to be solved to test form submission.

2022-11-17 06:48 UTC, kevinmamaqi approved these changes

2022-11-17 06:48 UTC, merged