592 fix register response success notification
IT-Academy-BCN/ita-directory pull request #819
Opened 2022-11-21 11:31 UTC by adaldin

Fixed tests on Registration. All passed

2022-11-21 11:51 UTC, kevinmamaqi requested changes

2022-11-21 11:51 UTC, kevinmamaqi commented on frontend/src/__test__/pages/UserFlow/Registration/Registration.test.jsx
> +  it('should call onSubmit when all fields pass validation', async () => {
En el test estas validando que sale el mensaje de exito, pero el proceso creo que es:

- Pinchar onSubmit (test aquí de que se ha llamado 1 vez) -> `expect(handleSubmit).toHaveBeenCalledTimes(1)`
- Validar:
   1. Exito: (otro test), este seria el que tienes, que valida.
   2. Error: faltaria.

2022-11-29 11:18 UTC, adaldin commented on frontend/src/__test__/pages/UserFlow/Registration/Registration.test.jsx
> +  it('should call onSubmit when all fields pass validation', async () => {
Aquí he ido a la documentación de MSW y lo que me dice es que en cuanto haga el server. listen() (en setupTest.js) luego ya puedo testear si aparece o no un elemento "x" como respuesta de ese mock (en este caso la notificación. Me dices si quieres  cualquier cosa si quieres que testee algo más.

2022-12-01 10:29 UTC, kevinmamaqi approved these changes

2022-12-01 10:29 UTC, merged