Add Edit button and link to edit ad in my-ads
IT-Academy-BCN/ita-directory pull request #866
Opened 2023-03-01 09:39 UTC by Lahali

This page is linked to EditAd, that has an open issue
close #826

2023-03-01 09:42 UTC, kevinmamaqi requested changes

2023-03-01 09:42 UTC, kevinmamaqi commented on backend/app/schemas/ConversationSchema.js
> -  userId: z.number().int(),
Hola @Lahali ¿este cambio que tiene que ver con el PR actual? Creo que tendría que estar aquí

2023-03-01 09:42 UTC, kevinmamaqi commented on backend/prisma/seed.js
> +/* eslint-disable @typescript-eslint/naming-convention */
Este cambio no es necesario, no deberías de cambiar el seed.js en este PR

2023-03-01 09:42 UTC, kevinmamaqi commented on frontend/src/pages/AdList/AdCard/AdCard.jsx
> +        <Link to="/edit-ad" style={{ textDecoration: 'none' }}>
Aquí debería de haber un condicional en AdCard para saber si es un anuncio del propio usuario o no, si lo es se debe mostrar editar, sino, contactar.

2023-03-01 09:54 UTC, Lahali commented on backend/prisma/seed.js
> +/* eslint-disable @typescript-eslint/naming-convention */
Ok

2023-03-01 09:56 UTC, Lahali commented on frontend/src/pages/AdList/AdCard/AdCard.jsx
> +        <Link to="/edit-ad" style={{ textDecoration: 'none' }}>
Ok, ahora lo reviso

2023-03-01 11:53 UTC, Lahali commented on frontend/src/pages/AdList/AdCard/AdCard.jsx
> +        <Link to="/edit-ad" style={{ textDecoration: 'none' }}>
@kevinmamaqi Estoy revisando este condicional y tengo un par de problemas, por un lado no encuentro referencia específica sobre quién ha escrito el anuncio, y por otro lado yo estoy trabajando en el link my-ads, ahí entiendo que todos los anuncios que deberían aparecer ya son los publicados por el propio usuario y donde iría el condicional es en el link anuncios (el general)

2023-03-02 10:05 UTC, Lahali commented
En los anuncios ya se puede ver el botón edit o contact dependiendo de si el anuncio es del usuario logueado o de otro.
Todos los anuncios se han subido desde el mismo usuario. 
Para ver botón de Editar, hacer login con:
email: test@test.test
password: Test-test99
Para ver botón Contactar, hacer login con cualquier otro usuario.

2023-03-02 11:56 UTC, kevinmamaqi approved these changes

2023-03-02 11:56 UTC, merged