852-fix-styles-individual-ad
IT-Academy-BCN/ita-directory pull request #872
Opened 2023-03-06 21:56 UTC by Lahali

2023-03-07 07:32 UTC, kevinmamaqi commented
@Lahali hay conflictos

2023-03-07 09:49 UTC, kevinmamaqi requested changes

2023-03-07 09:49 UTC, kevinmamaqi commented on frontend/src/pages/Ad/Ad.tsx
> +    /* padding-top: 0.5rem;
Elimina comentarios

2023-03-07 09:49 UTC, kevinmamaqi commented on frontend/src/pages/Ad/Ad.tsx
> +  font-size: 12px;
Cogelo de dimensions

2023-03-07 09:49 UTC, kevinmamaqi commented on frontend/src/pages/Ad/Ad.tsx
> +  width: 100vw;
Me chirria un poco esto. 100% mejor.

2023-03-07 21:33 UTC, Lahali commented on frontend/src/pages/Ad/Ad.tsx
> +  font-size: 12px;
Corregido

2023-03-07 21:34 UTC, Lahali commented on frontend/src/pages/Ad/Ad.tsx
> +  width: 100vw;
Corregido

2023-03-07 21:34 UTC, Lahali commented
Ya están hechas las correcciones

2023-03-08 08:12 UTC, kevinmamaqi approved these changes

2023-03-08 08:12 UTC, merged