886-migrate-ErrorMessage-into-typescript
IT-Academy-BCN/ita-directory pull request #903
Opened 2023-03-13 16:06 UTC by Lahali

2023-03-14 07:56 UTC, kevinmamaqi requested changes

2023-03-14 07:56 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/ErrorMessage.tsx
> +interface ErrorMessageProps {
Mejor utilizar types en toda la app, y que además se definan como TErrorMessage (T Delante del nombre del componente).

2023-03-14 07:56 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/ErrorMessage.tsx
> +function ErrorMessage({ text }: ErrorMessageProps) {
Prueba a hacer que sea un simple styled-component en lugar de un componente de React

2023-03-14 07:56 UTC, kevinmamaqi commented
También añade un TEST @Lahali

2023-03-14 17:14 UTC, Lahali commented on frontend/src/components/atoms/Forms/ErrorMessage.tsx
> +interface ErrorMessageProps {
Hecho

2023-03-14 17:14 UTC, Lahali commented on frontend/src/components/atoms/Forms/ErrorMessage.tsx
> +function ErrorMessage({ text }: ErrorMessageProps) {
Hecho

2023-03-14 17:15 UTC, Lahali commented
Convertí el componente en un styled-component y añadí el test.

2023-03-15 06:13 UTC, kevinmamaqi-90poe requested changes

2023-03-15 06:13 UTC, kevinmamaqi-90poe commented on frontend/src/__test__/atoms/ErrorMessage.test.tsx
> +    render(<ErrorMessage data-testid="error-message" />)
Aquí lo más importanete además de pasarle props y los estilos es que renderice texto.

2023-03-15 08:07 UTC, kevinmamaqi approved these changes

2023-03-15 08:21 UTC, merged